#!/bin/bash
# ============================================================
#  OzBot — One-Command Setup Script
#  Run this on a fresh Ubuntu 22.04 VPS:
#  bash setup.sh
# ============================================================

set -e

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
RESET="\033[0m"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║       OzBot Trading Bot — Setup          ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}"
echo ""

# ── 1. System dependencies ──────────────────────────────────
echo -e "${YELLOW}[1/5] Installing system dependencies...${RESET}"
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv git
echo -e "${GREEN}✅ System dependencies installed${RESET}"

# ── 2. Python virtual environment ───────────────────────────
echo ""
echo -e "${YELLOW}[2/5] Setting up Python environment...${RESET}"
cd /root/binancebot
python3 -m venv .venv
.venv/bin/pip install --upgrade pip -q
.venv/bin/pip install -r requirements.txt -q
echo -e "${GREEN}✅ Python environment ready${RESET}"

# ── 3. Collect user config ──────────────────────────────────
echo ""
echo -e "${YELLOW}[3/5] Configuration setup${RESET}"
echo -e "${BOLD}Please enter your details (press Enter after each one):${RESET}"
echo ""

read -p "  Binance API Key:          " BINANCE_API_KEY
read -p "  Binance API Secret:       " BINANCE_API_SECRET
echo ""
read -p "  Telegram Bot Token:       " TELEGRAM_TOKEN
read -p "  Telegram Chat ID:         " TELEGRAM_CHAT_ID
echo ""
read -p "  Telegram API ID:          " TELEGRAM_API_ID
read -p "  Telegram API Hash:        " TELEGRAM_API_HASH
echo ""
read -p "  Signal Channel URL:       " SIGNAL_CHANNEL
echo ""
read -p "  Gemini API Key (optional, press Enter to skip): " GEMINI_API_KEY
echo ""

echo -e "${YELLOW}Trading environment:${RESET}"
echo "  1) live    — real money (recommended once tested)"
echo "  2) testnet — paper trading (safe for testing)"
read -p "  Choose [1/2]: " ENV_CHOICE
if [ "$ENV_CHOICE" = "2" ]; then
    TRADING_ENV="testnet"
else
    TRADING_ENV="live"
fi

# ── 4. Write .env file ──────────────────────────────────────
echo ""
echo -e "${YELLOW}[4/5] Writing configuration...${RESET}"

cat > /root/binancebot/.env << EOF
# OzBot Configuration — generated by setup.sh

BINANCE_API_KEY=${BINANCE_API_KEY}
BINANCE_API_SECRET=${BINANCE_API_SECRET}
TRADING_ENV=${TRADING_ENV}

SYMBOL=BTC/USDT:USDT
TIMEFRAME=4h
EMA_PERIOD=50
RSI_PERIOD=14
ATR_PERIOD=14
ATR_STOP_MULTIPLIER=1.5
ATR_TRAIL_MULTIPLIER=2.0
RSI_ENTRY_THRESHOLD=55
ADX_THRESHOLD=20
VOLUME_FILTER=true
SR_LOOKBACK=20
SR_ZONE_ATR_MULT=0.5
MACD_FILTER=false
MACD_FAST=12
MACD_SLOW=26
MACD_SIGNAL=9
HTF_FILTER=false
HTF_TIMEFRAME=1d
HTF_EMA_PERIOD=50

SCANNER_ENABLED=true
SCAN_PAIRS=BTC/USDT:USDT,ETH/USDT:USDT,SOL/USDT:USDT,XRP/USDT:USDT,BNB/USDT:USDT,DOGE/USDT:USDT,ADA/USDT:USDT,AVAX/USDT:USDT,DOT/USDT:USDT,LINK/USDT:USDT

RISK_PER_TRADE_PCT=0.01
MAX_LEVERAGE=10
DAILY_LOSS_LIMIT_PCT=0.05
MAX_DRAWDOWN_PCT=0.15
MAX_CONSECUTIVE_LOSSES=3
DRAWDOWN_ALERT_PCT=10.0

TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

TELEGRAM_API_ID=${TELEGRAM_API_ID}
TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
SIGNAL_CHANNEL=${SIGNAL_CHANNEL}

GEMINI_API_KEY=${GEMINI_API_KEY}
EOF

chmod 600 /root/binancebot/.env
echo -e "${GREEN}✅ Configuration saved${RESET}"

# ── 5. Systemd service ──────────────────────────────────────
echo ""
echo -e "${YELLOW}[5/5] Installing systemd service...${RESET}"

mkdir -p /root/binancebot/logs

cat > /etc/systemd/system/binancebot.service << EOF
[Unit]
Description=OzBot Binance Trading Bot
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/binancebot
ExecStart=/root/binancebot/.venv/bin/python main.py
Restart=always
RestartSec=10
StandardOutput=append:/root/binancebot/logs/bot.log
StandardError=append:/root/binancebot/logs/bot.log

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable binancebot
echo -e "${GREEN}✅ Systemd service installed${RESET}"

# ── Done ────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║           Setup Complete! 🚀             ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT — Telegram Login Required:${RESET}"
echo "   The bot uses your Telegram account to read signal channels."
echo "   Run this once to log in:"
echo ""
echo -e "   ${BOLD}cd /root/binancebot && .venv/bin/python -c \"from telethon.sync import TelegramClient; c = TelegramClient('session', $(grep TELEGRAM_API_ID .env | cut -d= -f2), '$(grep TELEGRAM_API_HASH .env | cut -d= -f2)'); c.start(); print('Login successful!')\"${RESET}"
echo ""
echo "   Then start the bot:"
echo -e "   ${BOLD}systemctl start binancebot${RESET}"
echo ""
echo "   Watch the logs:"
echo -e "   ${BOLD}tail -f /root/binancebot/logs/bot.log${RESET}"
echo ""
echo -e "${GREEN}Open Telegram and message your bot to test it!${RESET}"
echo ""
